/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TransacoesRouteImport } from './routes/transacoes'
import { Route as RelatoriosRouteImport } from './routes/relatorios'
import { Route as CalculadorasRouteImport } from './routes/calculadoras'
import { Route as AjustesRouteImport } from './routes/ajustes'
import { Route as AdicionarRouteImport } from './routes/adicionar'
import { Route as IndexRouteImport } from './routes/index'

const TransacoesRoute = TransacoesRouteImport.update({
  id: '/transacoes',
  path: '/transacoes',
  getParentRoute: () => rootRouteImport,
} as any)
const RelatoriosRoute = RelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => rootRouteImport,
} as any)
const CalculadorasRoute = CalculadorasRouteImport.update({
  id: '/calculadoras',
  path: '/calculadoras',
  getParentRoute: () => rootRouteImport,
} as any)
const AjustesRoute = AjustesRouteImport.update({
  id: '/ajustes',
  path: '/ajustes',
  getParentRoute: () => rootRouteImport,
} as any)
const AdicionarRoute = AdicionarRouteImport.update({
  id: '/adicionar',
  path: '/adicionar',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/adicionar': typeof AdicionarRoute
  '/ajustes': typeof AjustesRoute
  '/calculadoras': typeof CalculadorasRoute
  '/relatorios': typeof RelatoriosRoute
  '/transacoes': typeof TransacoesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/adicionar': typeof AdicionarRoute
  '/ajustes': typeof AjustesRoute
  '/calculadoras': typeof CalculadorasRoute
  '/relatorios': typeof RelatoriosRoute
  '/transacoes': typeof TransacoesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/adicionar': typeof AdicionarRoute
  '/ajustes': typeof AjustesRoute
  '/calculadoras': typeof CalculadorasRoute
  '/relatorios': typeof RelatoriosRoute
  '/transacoes': typeof TransacoesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/adicionar'
    | '/ajustes'
    | '/calculadoras'
    | '/relatorios'
    | '/transacoes'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/adicionar'
    | '/ajustes'
    | '/calculadoras'
    | '/relatorios'
    | '/transacoes'
  id:
    | '__root__'
    | '/'
    | '/adicionar'
    | '/ajustes'
    | '/calculadoras'
    | '/relatorios'
    | '/transacoes'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdicionarRoute: typeof AdicionarRoute
  AjustesRoute: typeof AjustesRoute
  CalculadorasRoute: typeof CalculadorasRoute
  RelatoriosRoute: typeof RelatoriosRoute
  TransacoesRoute: typeof TransacoesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/transacoes': {
      id: '/transacoes'
      path: '/transacoes'
      fullPath: '/transacoes'
      preLoaderRoute: typeof TransacoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/relatorios': {
      id: '/relatorios'
      path: '/relatorios'
      fullPath: '/relatorios'
      preLoaderRoute: typeof RelatoriosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calculadoras': {
      id: '/calculadoras'
      path: '/calculadoras'
      fullPath: '/calculadoras'
      preLoaderRoute: typeof CalculadorasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ajustes': {
      id: '/ajustes'
      path: '/ajustes'
      fullPath: '/ajustes'
      preLoaderRoute: typeof AjustesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/adicionar': {
      id: '/adicionar'
      path: '/adicionar'
      fullPath: '/adicionar'
      preLoaderRoute: typeof AdicionarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdicionarRoute: AdicionarRoute,
  AjustesRoute: AjustesRoute,
  CalculadorasRoute: CalculadorasRoute,
  RelatoriosRoute: RelatoriosRoute,
  TransacoesRoute: TransacoesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
